ersion: "3.9"

services:
  db:
    image: mariadb:latest
    container_name: mydb
    restart: unless-stopped
    env_file: .env
    networks:
      - app-network

  webserver:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
